openapi: 3.0.1
info:
  title: Employee Management API
  description: API for managing employees, departments, projects, and their relationships.
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /department:
    get:
      summary: Get all departments
      operationId: getAllDepartments
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
      responses:
        '200':
          description: A list of departments
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    dept_id:
                      type: integer
                    dept_name:
                      type: string
                    location:
                      type: string

    post:
      summary: Create a new department
      operationId: createDepartment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                dept_name:
                  type: string
                location:
                  type: string
      responses:
        '201':
          description: Department created
          content:
            application/json:
              schema:
                type: object
                properties:
                  dept_id:
                    type: integer
                  dept_name:
                    type: string
                  location:
                    type: string

  /department/{id}:
    get:
      summary: Get a department by ID
      operationId: getDepartmentById
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Department details
          content:
            application/json:
              schema:
                type: object
                properties:
                  dept_id:
                    type: integer
                  dept_name:
                    type: string
                  location:
                    type: string

    put:
      summary: Update a department by ID
      operationId: updateDepartment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                dept_name:
                  type: string
                location:
                  type: string
      responses:
        '200':
          description: Department updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  dept_id:
                    type: integer
                  dept_name:
                    type: string
                  location:
                    type: string
